package S4.Topicos_especiais_em_Programacao.Atividade10_04etapa02.Questao04;
import javax.swing.JOptionPane;

/**
 *
 * @author 1manuelc
 */
public class CalculadoraINSS extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraINSS
     */
    public CalculadoraINSS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        painelDadosPessoais = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        comboBoxSexo = new javax.swing.JComboBox<>();
        tituloFrame = new javax.swing.JLabel();
        painelCalculoSalario = new javax.swing.JPanel();
        labelValorHora = new javax.swing.JLabel();
        labelQtdHoras = new javax.swing.JLabel();
        txtValorHora = new javax.swing.JTextField();
        txtQtdeHoras = new javax.swing.JTextField();
        painelResultado = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        labelDescontoINSS = new javax.swing.JLabel();
        txtDescontoINSS = new javax.swing.JTextField();
        labelSalarioLiquido = new javax.swing.JLabel();
        txtSalarioLiquido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painelDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        labelNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        labelIdade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelIdade.setText("Idade:");

        labelSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSexo.setText("Sexo:");

        labelEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelEndereco.setText("Endereço");

        comboBoxSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não binário" }));
        comboBoxSexo.setSelectedIndex(-1);

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndereco))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(txtIdade)
                                .addGap(18, 18, 18)
                                .addComponent(labelSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNome))))
                .addGap(16, 16, 16))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdade)
                    .addComponent(labelSexo)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tituloFrame.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        tituloFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFrame.setText("Cálculo de Salário Líquido - Desconto do INSS");

        painelCalculoSalario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cálculo do Salário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        labelValorHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelValorHora.setText("Valor da hora trabalhada:");

        labelQtdHoras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelQtdHoras.setText("Horas trabalhadas:");

        txtValorHora.setToolTipText("Não deve exceder R$ 200,00");
        txtValorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorHoraActionPerformed(evt);
            }
        });

        txtQtdeHoras.setToolTipText("Não exceder 40hrs");

        javax.swing.GroupLayout painelCalculoSalarioLayout = new javax.swing.GroupLayout(painelCalculoSalario);
        painelCalculoSalario.setLayout(painelCalculoSalarioLayout);
        painelCalculoSalarioLayout.setHorizontalGroup(
            painelCalculoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalculoSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCalculoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCalculoSalarioLayout.createSequentialGroup()
                        .addComponent(labelValorHora)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelCalculoSalarioLayout.createSequentialGroup()
                        .addComponent(labelQtdHoras)
                        .addGap(18, 18, 18)
                        .addComponent(txtQtdeHoras)))
                .addContainerGap())
        );
        painelCalculoSalarioLayout.setVerticalGroup(
            painelCalculoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalculoSalarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(painelCalculoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorHora)
                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCalculoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQtdHoras)
                    .addComponent(txtQtdeHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, painelGeralLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(painelDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGeralLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(painelCalculoSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tituloFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCalculoSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        painelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        labelDescontoINSS.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        labelDescontoINSS.setText("Desconto do INSS:");

        txtDescontoINSS.setEnabled(false);

        labelSalarioLiquido.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        labelSalarioLiquido.setText("Salário Líquido:");

        txtSalarioLiquido.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        txtSalarioLiquido.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout painelResultadoLayout = new javax.swing.GroupLayout(painelResultado);
        painelResultado.setLayout(painelResultadoLayout);
        painelResultadoLayout.setHorizontalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResultadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSalarioLiquido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSalarioLiquido)
                    .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelResultadoLayout.createSequentialGroup()
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelResultadoLayout.createSequentialGroup()
                            .addComponent(labelDescontoINSS)
                            .addGap(18, 18, 18)
                            .addComponent(txtDescontoINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        painelResultadoLayout.setVerticalGroup(
            painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelResultadoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescontoINSS)
                    .addComponent(txtDescontoINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(labelSalarioLiquido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(painelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorHoraActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText("");
        txtIdade.setText("");
        txtEndereco.setText("");
        comboBoxSexo.setSelectedIndex(-1);
        
        txtDescontoINSS.setText("");
        txtValorHora.setText("");
        txtQtdeHoras.setText("");
        txtSalarioLiquido.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    public double obterSalarioPorFaixa(double valorHoras, int qtdeHoras) {
        double salario = valorHoras * qtdeHoras;
            
        if (salario == 1320.00) {
            salario *= 0.925;
            txtDescontoINSS.setText("7.5%");
        } else if (salario < 2571.30) {
            salario *= 0.91;
            txtDescontoINSS.setText("9%");
        } else if (salario < 3856.95) {
            salario *= 0.88;
            txtDescontoINSS.setText("12%");
        } else {
            salario *= 0.86;
            txtDescontoINSS.setText("14%");
        } 
        
        return salario;
    }
    
    public boolean haAlgumCampoVazio() {
        if("".equals(txtNome.getText())) return true;
        else if("".equals(txtIdade.getText())) return true;
        else if("".equals(txtEndereco.getText())) return true;
        else if(comboBoxSexo.getSelectedIndex() == -1) return true;
        else if("".equals(txtValorHora.getText())) return true;
        else if("".equals(txtQtdeHoras.getText())) return true;
        return false;
    }
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            if (haAlgumCampoVazio()) {
                JOptionPane.showMessageDialog(
                    null,
                    "Preencha todos os campos para calcular corretamente!",
                    "Entradas Inválidas!",
                    JOptionPane.WARNING_MESSAGE
                );
                
            } else {
                double valorHoras = Double.parseDouble(txtValorHora.getText());
                int qtdeHoras = Integer.parseInt(txtQtdeHoras.getText());

                if (valorHoras > 200.00 || qtdeHoras > 40) {
                    if (valorHoras > 200.00) {
                        JOptionPane.showMessageDialog(
                                null,
                                "Seu valor por hora não pode ser acima de R$ 200,00",
                                "Entrada Inválida!",
                                JOptionPane.WARNING_MESSAGE
                        );
                    }

                    if (qtdeHoras > 40) {
                        JOptionPane.showMessageDialog(
                                null,
                                "Sua quantidade de horas não pode ser acima de 40h",
                                "Entrada Inválida!",
                                JOptionPane.WARNING_MESSAGE
                        );
                    }

                } else {
                    txtSalarioLiquido.setText(String.format(
                            "R$ %.2f", obterSalarioPorFaixa(valorHoras, qtdeHoras))
                    );
                }
            }
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Digite números válidos!",
                    "Entradas Inválidas!",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraINSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraINSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraINSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraINSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraINSS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JLabel labelDescontoINSS;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelQtdHoras;
    private javax.swing.JLabel labelSalarioLiquido;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelValorHora;
    private javax.swing.JPanel painelCalculoSalario;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelResultado;
    private javax.swing.JLabel tituloFrame;
    private javax.swing.JTextField txtDescontoINSS;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtdeHoras;
    private javax.swing.JLabel txtSalarioLiquido;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
