USE BD_TESTE

ALTER TABLE tbCurso
	ADD CONSTRAINT UK_CUR_NOME UNIQUE (CUR_CODIGO),
				   UK_CUR_CARGA_HORARIA INT UNIQUE (CUR_CARGA_HORARIA) -- Não entendi pq pediu o tipo ??

ALTER TABLE tbDisciplina
	ADD CUR_CODIGO INT NOT NULL,
	CONSTRAINT FK_CUR_CODIGO FOREIGN KEY (CUR_CODIGO) REFERENCES tbCurso(CUR_CODIGO)

ALTER TABLE tbCurso
	DROP CONSTRAINT UK_CUR_CARGA_HORARIA -- remoção de chave

DROP TABLE tbDisciplina