CREATE DATABASE BD_PEDIDO
USE BD_PEDIDO

CREATE TABLE tbSECAO (
	SEC_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	SEC_NOME VARCHAR(20) NOT NULL
)

CREATE TABLE tbVENDEDOR (
	VEN_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	VEN_NOME VARCHAR(30) NOT NULL,
	VEN_CPF VARCHAR(14) NOT NULL UNIQUE
)

CREATE TABLE tbCLIENTE (
	CLI_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	CLI_NOME VARCHAR(30) NOT NULL,
	CLI_CPF VARCHAR(14) NOT NULL UNIQUE,
	CLI_RUA VARCHAR(30) NOT NULL,
	CLI_NUMERO INT NULL,
	CLI_BAIRRO VARCHAR(30) NOT NULL,
	CLI_SEXO VARCHAR(1) NOT NULL
)

CREATE TABLE tbPRODUTO (
	PRO_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	PRO_NOME VARCHAR(30) NOT NULL,
	PRO_QTDE INT NOT NULL,
	PRO_UNIDADE VARCHAR(5) NOT NULL,
	PRO_PRECO_UNIT DECIMAL(10,2) NOT NULL,
	SEC_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbSECAO(SEC_CODIGO)
)

/* Regras para possível remoção da relação-destino da chave com ON DELETE:
	NO ACTION (não deixa remover a relação-destino da FK) [REGRA PADRÃO]
	CASCADE (remove a tupla que possui a FK) [Merece atenção]
	SET NULL (FK na tupla substituída por NULL) [ATRIBUTO PRECISA SER ANULÁVEL] 
*/

CREATE TABLE tbPedido (
	PED_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	PED_NUMERO INT NOT NULL UNIQUE,
	PED_DATA DATE NOT NULL,
	CLI_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbCLIENTE(CLI_CODIGO),
	VEN_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbVENDEDOR(VEN_CODIGO)
)

CREATE TABLE tbPEDIDOPRODUTO (
	PEP_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	PED_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbPEDIDO(PED_CODIGO),
	PRO_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbPRODUTO(PRO_CODIGO),
	PEP_QTDE INT NOT NULL,
	PEP_PRECO_UNIT DECIMAL(10,2) NOT NULL
)