CREATE DATABASE BD_BIBLIOTECA
USE BD_BIBLIOTECA

CREATE TABLE tbALUNO (
	ALU_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	ALU_NOME VARCHAR(30) NOT NULL,
	ALU_CPF VARCHAR(14) NOT NULL UNIQUE,
	ALU_DATA_NASC DATE NOT NULL,
	ALU_RUA VARCHAR(30) NOT NULL,
	ALU_NUMERO INT NULL,
	ALU_BAIRRO VARCHAR(30) NOT NULL,
	ALU_CIDADE VARCHAR(30) NOT NULL
)

CREATE TABLE tbALUNOTELEFONE (
	ALT_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	ALU_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbALUNO(ALU_CODIGO),
	ALT_TELEFONE INT NOT NULL
)

CREATE TABLE tbLIVRO (
	LIV_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	LIV_NOME VARCHAR(30) NOT NULL,
	LIV_ISBN VARCHAR(10) NOT NULL UNIQUE,
	LIV_EDICAO INT NOT NULL,
	LIV_VOLUME INT NOT NULL,
	LIV_EDITORA VARCHAR(30) NOT NULL,
	LIV_QTDE_EXEMP INT NOT NULL
)

CREATE TABLE tbAUTOR (
	AUT_CODIGO INT NOT NULL PRIMARY KEY,
	AUT_NOME VARCHAR(30) NOT NULL,
	AUT_NOTA_BIOG VARCHAR(300)
)

CREATE TABLE tbLIVROAUTOR (
	LIA_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	LIV_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbLIVRO(LIV_CODIGO),
	AUT_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbAUTOR(AUT_CODIGO)
)

CREATE TABLE tbLOCACAO (
	LOC_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	LOC_NUMERO INT NOT NULL UNIQUE,
	LOC_DATA DATE NOT NULL,
	ALU_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbALUNO(ALU_CODIGO)
)

CREATE TABLE tbLOCACAOLIVRO (
	LOL_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	LOC_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbLOCACAO(LOC_CODIGO),
	LIV_CODIGO INT NOT NULL FOREIGN KEY REFERENCES tbLIVRO(LIV_CODIGO),
	LOL_DATA_DEV DATE NOT NULL,
	LOL_MULTA DECIMAL(10,2) NULL
)