CREATE DATABASE BD_TESTE
USE BD_TESTE

CREATE TABLE tbCURSO (
	CUR_CODIGO INT NOT NULL,
	CUR_NOME VARCHAR(30) NOT NULL,
	CUR_CARGA_HORARIA INT NOT NULL UNIQUE
)

CREATE TABLE tbDISCIPLINA (
	DIS_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	DIS_NOME VARCHAR(30) NOT NULL,
	DIS_SIGLA VARCHAR(5) NOT NULL
)

ALTER TABLE tbDISCIPLINA
	ADD DIS_CARGA_HORARIA INT NOT NULL--, 
		-- CUR_CODIGO INT NOT NULL (para adicionar + de 1)
	-- Adicionar atributo(s)
	/* Obs: Se já houverem valores preenchidos na tabela atual, os valores
	futuros devem ser anuláveis (NULL) */

ALTER TABLE tbCURSO
	ALTER COLUMN CUR_NOME VARCHAR(50) NOT NULL
	-- Alteração de tipo e anulabilidade de atributo

ALTER TABLE tbDISCIPLINA
	DROP COLUMN DIS_SIGLA--,
				-- DIS_NOME (para remover + de 1)
	-- Remoção de atributo

ALTER TABLE tbCURSO
	ADD CONSTRAINT PK_CUR_CODIGO PRIMARY KEY (CUR_CODIGO)
	-- Chaves são consideradas restrições

ALTER TABLE tbDISCIPLINA
	ADD CONSTRAINT FK_CUR_CODIGO FOREIGN KEY (CUR_CODIGO) REFERENCES tbCURSO(CUR_CODIGO)