package S4.Topicos_especiais_em_Programacao.Atividade08_04etapa02.atv04_questao03.src.main.java.manuelc.atv04_questao03;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author manuelc
 */
public class LerVogal extends javax.swing.JFrame {

    /**
     * Creates new form AnalisarVogal
     */
    public LerVogal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVogal = new javax.swing.JTextField();
        btnLer = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leitura de Vogais");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Leitura de Vogais");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Digite a vogal:");

        txtVogal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVogalActionPerformed(evt);
            }
        });

        btnLer.setBackground(new java.awt.Color(102, 102, 102));
        btnLer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLer.setForeground(new java.awt.Color(255, 255, 255));
        btnLer.setText("Ler");
        btnLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVogal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVogal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String reconhecerOS() {
        try {
            String os = System.getProperty("os.name").toLowerCase();
            if (os.contains("win")) return "win";
            else return "others";
        } catch(Exception e) {
            JOptionPane.showMessageDialog(
                        null,
                        "Não foi possível reconhecer seu Sistema Operacional!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
            return "null";
        }
    }
    
    private void reproduzirVogal(String caminhoArquivo) {
        try {
            File caminho =  new File(caminhoArquivo);
            
            if(caminho.exists()) {
                AudioInputStream audio = AudioSystem.getAudioInputStream(caminho);
                Clip clipe = AudioSystem.getClip();
                clipe.open(audio);
                clipe.start();
                
            } else
                JOptionPane.showMessageDialog(
                        null,
                        "Arquivo de áudio não encontrado!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(
                        null,
                        "Erro inesperado!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
        }
    }
    
    private void reconhecerVogal(String vogal, String os) {
        try {
            String diretorioAudios = "";
            if("win".equals(os)) 
                diretorioAudios = "src\\main\\java\\manuelc\\atv04_questao03\\audios\\";
            else if("others".equals(os)) 
                diretorioAudios = "src/main/java/manuelc/atv04_questao03/audios/";
            
            switch (vogal) {
                case "A":
                    reproduzirVogal(diretorioAudios + "a_ma.wav");
                    break;
                case "a":
                    reproduzirVogal(diretorioAudios + "a_mi.wav");
                    break;
                case "E":
                    reproduzirVogal(diretorioAudios + "e_ma.wav");
                    break;
                case "e":
                    reproduzirVogal(diretorioAudios + "e_mi.wav");
                    break;
                case "I":
                    reproduzirVogal(diretorioAudios + "i_ma.wav");
                    break;
                case "i":
                    reproduzirVogal(diretorioAudios + "i_mi.wav");
                    break;
                    case "O":
                    reproduzirVogal(diretorioAudios + "o_ma.wav");
                    break;
                case "o":
                    reproduzirVogal(diretorioAudios + "o_mi.wav");
                    break;
                case "U":
                    reproduzirVogal(diretorioAudios + "u_ma.wav");
                    break;
                case "u":
                    reproduzirVogal(diretorioAudios + "u_mi.wav");
                    break;
                default:
                    reproduzirVogal(diretorioAudios + "0_none.wav");
                    break;
            }  
        } catch(Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        "Não foi possível abrir os arquivos de áudio!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
            }
    }
    
    private void txtVogalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVogalActionPerformed

    }//GEN-LAST:event_txtVogalActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtVogal.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerActionPerformed
        reconhecerVogal(txtVogal.getText(), reconhecerOS());
    }//GEN-LAST:event_btnLerActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LerVogal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LerVogal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LerVogal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LerVogal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LerVogal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLer;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtVogal;
    // End of variables declaration//GEN-END:variables
}
